services:
  db:
    image: postgres:latest
    restart: always
    expose:
      - "5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_app
    ports:
      - "5432:5432"
volumes:
  db: