spring:
  application:
    name: web4
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/task_app
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
server:
  port: 8080